<?php

declare(strict_types=1);

namespace LuaPhp\Runtime;

use LuaPhp\Compiler\ChunkId;
use LuaPhp\Compiler\CompileError;
use LuaPhp\Compiler\Compiler;
use LuaPhp\Compiler\Dump;
use LuaPhp\Compiler\Proto;
use LuaPhp\Compiler\Undump;
use LuaPhp\Emitter\Emitter;
use LuaPhp\Lib\Io\CFile;
use LuaPhp\Lib\Io\Errno;

/**
 * Chunks -> Lua functions (lapi.c: lua_load, ldo.c: f_parser/checkmode,
 * lauxlib.c: luaL_loadfilex).
 *
 * load(): source text goes through Compiler::compile, binary chunks
 * through Undump::undump; the Proto is emitted as PHP and eval'd. A chunk
 * loaded before comes from LoadCache instead (by its bytes and chunk
 * name, in memory or on disk). PHP never frees eval'd code's runtime
 * caches, so factories are also cached by their PHP source: loading the
 * same code again reuses the compiled code.
 *
 * Files: bin/lua compiles them like load(). In scripts bin/lua2php
 * generates (GlobalState::$filesArePrecompiled), every Lua file was
 * transpiled ahead of time: loadFile never reads a Lua file, it includes
 * the PHP bin/lua2php generated where the Lua file would be
 * (precompiledFileName), see loadPrecompiled.
 *
 * @internal
 */
final class ChunkLoader
{
    private const FACTORY_CACHE_LIMIT = 1000;

    /** 'format' of the chunk a file bin/lua2php generated returns (see loadPrecompiled) */
    public const PRECOMPILED_FORMAT = 'luaphp-chunk-1';

    /**
     * How every file bin/lua2php generates starts, followed by the name of
     * the Lua file it came from (rawurlencode'd, without directories) and
     * a newline. Any other PHP file is never included, and a generated
     * file only stands for that Lua file ("mod" and "mod.lua" both map to
     * mod.php).
     */
    public const PRECOMPILED_HEADER = "<?php\n\n// Generated by bin/lua2php from ";

    /**
     * Set while the runtime includes a file bin/lua2php generated: the
     * file then returns its chunk instead of running as a script.
     */
    public static bool $includingPrecompiled = false;

    /** @var array<string, \Closure> PHP source hash => factory (see Emitter) */
    private static array $factoryCache = [];

    /**
     * lapi.c: lua_load. Returns the main function of $chunk with its first
     * upvalue (_ENV) set to the global table, or throws
     * LuaError(LUA_ERRSYNTAX) with Lua's message.
     */
    public static function load(Coroutine $L, string $chunk, string $chunkname, ?string $mode): LuaClosure
    {
        // ldo.c: luaD_protectedparser: parse in protected mode, with the
        // current message handler for errors the parser raises as runtime
        // errors ("C stack overflow" and the like; PHP compiling the emitted
        // code can exhaust the C stack too, see Calls::cStackOverflowError)
        [$status, $result] = Calls::protectedRun($L, static function () use ($L, $chunk, $chunkname, $mode): LuaClosure {
            $isBinary = $chunk !== '' && $chunk[0] === Undump::LUA_SIGNATURE[0];
            self::checkMode($mode, $isBinary ? 'binary' : 'text');
            $countSteps = $L->globalState->countSteps;
            $key = LoadCache::key($chunk, $chunkname, $countSteps);
            $cached = LoadCache::find($key, $L->nCcalls);
            if ($cached !== null) {
                [$protos, $factory] = $cached;
                // fresh Protos, as a compile (one string per contents) or an undump makes
                return self::instantiate(Undump::undump($protos ?? $chunk, $chunkname, !$isBinary), $factory);
            }
            $L->globalState->budget?->chargeSteps(\strlen($chunk));  // (compiling costs more than a step per byte)
            $nesting = 0;
            try {
                $proto = $isBinary
                    ? Undump::undump($chunk, $chunkname)
                    : Compiler::compile($chunk, $chunkname, $L->nCcalls, $nesting);
            } catch (CompileError $error) {
                $status = match ($error->getCode()) {
                    Lua::LUA_ERRRUN => Lua::LUA_ERRRUN,
                    Lua::LUA_ERRERR => Lua::LUA_ERRERR,
                    default => Lua::LUA_ERRSYNTAX,
                };
                throw new LuaError($error->getMessage(), $status);
            }
            $factorySource = Emitter::emitChunk($proto, $countSteps);
            $factory = self::factoryForSource($factorySource);
            LoadCache::store($key, $isBinary ? null : Dump::dump($proto, false), $nesting, $factory, $factorySource);
            return self::instantiate($proto, $factory);
        }, $L->errfunc);
        if ($status !== Lua::LUA_OK) {
            throw new LuaError($result, $status);
        }
        $closure = $result;
        if ($closure->proto->upvalues !== []) {  // does it have an upvalue?
            $closure->getUpval(0)->v = $L->globalState->globals;  // set it to the global table
        }
        return $closure;
    }

    // ldo.c: checkmode
    private static function checkMode(?string $mode, string $kind): void
    {
        if ($mode !== null && !str_contains(DebugInfo::cString($mode), $kind[0])) {
            throw new LuaError("attempt to load a $kind chunk (mode is '" . DebugInfo::cString($mode) . "')", Lua::LUA_ERRSYNTAX);
        }
    }

    /**
     * lparser.c: enterlevel, as a function of the starting depth: the
     * error compiling a chunk raises when it starts at C-call depth
     * $nCcalls, given that its parse went $nesting levels deeper
     * (Compiler::compile), or null. Parsing does not depend on the depth
     * otherwise, so a chunk that compiled once compiles wherever this is
     * null.
     */
    public static function nestingError(int $nCcalls, int $nesting): ?LuaError
    {
        if ($nesting === 0) {
            return null;  // enterlevel never ran
        }
        $deepest = $nCcalls + $nesting;  // the levels reached: $nCcalls + 1 .. $deepest
        if ($nCcalls < Lua::LUAI_MAXCCALLS && $deepest >= Lua::LUAI_MAXCCALLS) {
            return new LuaError('C stack overflow', Lua::LUA_ERRRUN);
        }
        if ($deepest >= intdiv(Lua::LUAI_MAXCCALLS, 10) * 11) {
            return new LuaError('error in error handling', Lua::LUA_ERRERR);  // ldo.c: luaD_errerr
        }
        return null;
    }

    /**
     * A new closure for the main function $proto with fresh closed
     * upvalues (lfunc.c: luaF_initupvals).
     */
    public static function instantiate(Proto $proto, ?\Closure $factory = null): LuaClosure
    {
        $factory ??= self::factoryFor($proto);
        $upvalues = [];
        foreach ($proto->upvalues as $unused) {
            $upvalues[] = UpVal::closed(null);
        }
        return LuaClosure::create($proto, $factory($proto), $upvalues);
    }

    /** the compiled factory for a chunk whose main function is $proto */
    public static function factoryFor(Proto $proto): \Closure
    {
        return self::factoryForSource(Emitter::emitChunk($proto));
    }

    /** the compiled factory whose PHP source (Emitter::emitChunk) is $source */
    private static function factoryForSource(string $source): \Closure
    {
        $key = hash('xxh128', $source);
        $factory = self::$factoryCache[$key] ?? null;
        if ($factory !== null) {
            return $factory;
        }
        $factory = eval(Emitter::PREAMBLE . "\nreturn " . $source . ";\n");
        if (\count(self::$factoryCache) >= self::FACTORY_CACHE_LIMIT) {
            self::$factoryCache = [];
        }
        self::$factoryCache[$key] = $factory;
        return $factory;
    }

    /**
     * lauxlib.c: luaL_loadfilex: load a file (null: standard input),
     * skipping a UTF-8 BOM and a first line starting with '#'. Errors
     * opening or reading the file are LuaError(LUA_ERRFILE).
     */
    public static function loadFile(Coroutine $L, ?string $filename, ?string $mode): LuaClosure
    {
        if ($L->globalState->filesArePrecompiled) {
            return self::loadPrecompiledFile($L, $filename, $mode);
        }
        if ($filename === null) {
            $chunkname = '=stdin';
            $contents = stream_get_contents(STDIN);
            if ($contents === false) {
                throw new LuaError('cannot read stdin', Lua::LUA_ERRFILE);
            }
        } else {
            $filename = DebugInfo::cString($filename);  // C's fopen and "@%s" see a C string
            $chunkname = '@' . $filename;
            $file = self::openFile($filename);
            $contents = $file->readAll();
            $readFailed = $file->error;  // (a directory: C's fopen succeeds, its reads fail with EISDIR)
            $file->close();
            if ($readFailed) {
                throw new LuaError("cannot read $filename: " . Errno::strerror(Errno::$errno), Lua::LUA_ERRFILE);
            }
        }
        // lauxlib.c: skipBOM (an incomplete BOM keeps its first character, forcing an error)
        $position = 0;
        if (str_starts_with($contents, "\xEF\xBB\xBF")) {
            $position = 3;
        }
        $prefix = '';
        // lauxlib.c: skipcomment (first line starting with '#')
        if (($contents[$position] ?? '') === '#') {
            $newlinePosition = strpos($contents, "\n", $position);
            $position = $newlinePosition === false ? \strlen($contents) : $newlinePosition + 1;
            $prefix = "\n";  // add newline to correct line numbers
        }
        $chunk = substr($contents, $position);
        if (($chunk[0] ?? '') === Undump::LUA_SIGNATURE[0]) {  // binary file?
            $prefix = '';  // remove possible newline
        }
        return self::load($L, $prefix . $chunk, $chunkname, $mode);
    }

    /**
     * Where bin/lua2php puts the PHP for the Lua file $filename: "x.lua"
     * becomes "x.php"; other names get ".php" appended ("x" -> "x.php",
     * "x.luac" -> "x.luac.php").
     */
    public static function precompiledFileName(string $filename): string
    {
        return (str_ends_with($filename, '.lua') ? substr($filename, 0, -4) : $filename) . '.php';
    }

    /**
     * The name of the Lua file bin/lua2php generated $phpFile from (see
     * PRECOMPILED_HEADER), or null: no such file, or not generated by
     * bin/lua2php.
     */
    public static function precompiledFrom(string $phpFile): ?string
    {
        $start = @file_get_contents($phpFile, false, null, 0, 1024);  // room for a 255-byte name, encoded
        if (!\is_string($start) || !str_starts_with($start, self::PRECOMPILED_HEADER)) {
            return null;
        }
        $nameEnd = strpos($start, "\n", \strlen(self::PRECOMPILED_HEADER));
        if ($nameEnd === false) {
            return null;
        }
        return rawurldecode(substr($start, \strlen(self::PRECOMPILED_HEADER), $nameEnd - \strlen(self::PRECOMPILED_HEADER)));
    }

    /** whether the Lua file $filename was transpiled: its precompiled file came from it */
    public static function hasPrecompiledFile(string $filename): bool
    {
        $slash = strrpos($filename, '/');
        $name = $slash === false ? $filename : substr($filename, $slash + 1);
        return self::precompiledFrom(self::precompiledFileName($filename)) === $name;
    }

    /**
     * luaL_loadfilex in scripts bin/lua2php generates: loads the PHP
     * generated for $filename ahead of time, and never reads nor compiles
     * $filename itself. A Lua file without it (say, one the program wrote)
     * and standard input are errors (LUA_ERRFILE) saying so.
     */
    private static function loadPrecompiledFile(Coroutine $L, ?string $filename, ?string $mode): LuaClosure
    {
        if ($filename === null) {
            throw new LuaError('cannot load stdin: standard input cannot be transpiled ahead of time', Lua::LUA_ERRFILE);
        }
        $filename = DebugInfo::cString($filename);  // C's fopen sees a C string
        $phpFile = self::precompiledFileName($filename);
        if (!self::hasPrecompiledFile($filename)) {  // then it is as if only the Lua file were there
            if (!file_exists($filename) || is_dir($filename)) {  // say what C's fopen, or its first read, says
                $file = self::openFile($filename);
                $file->getc();  // (a directory: fails with EISDIR)
                $readFailed = $file->error;
                $file->close();
                if ($readFailed) {
                    throw new LuaError("cannot read $filename: " . Errno::strerror(Errno::$errno), Lua::LUA_ERRFILE);
                }
            }
            $from = self::precompiledFrom($phpFile);
            $why = match (true) {
                $from !== null => "$phpFile was generated from $from",
                is_file($phpFile) => "$phpFile was not generated by lua2php",
                default => "no $phpFile",
            };
            throw new LuaError("cannot load $filename: not transpiled ahead of time ($why)", Lua::LUA_ERRFILE);
        }
        self::$includingPrecompiled = true;
        try {
            // "./": relative to the working directory, as fopen is, not to include_path
            $chunk = @include($phpFile[0] === '/' ? $phpFile : './' . $phpFile);
        } catch (\ParseError) {
            $chunk = null;
        } finally {
            self::$includingPrecompiled = false;
        }
        if ($chunk === false) {
            throw new LuaError("cannot load $filename: cannot read $phpFile", Lua::LUA_ERRFILE);
        }
        if (!\is_array($chunk) || ($chunk['format'] ?? null) !== self::PRECOMPILED_FORMAT) {
            throw new LuaError("cannot load $filename: $phpFile holds no chunk (transpile it again)", Lua::LUA_ERRFILE);
        }
        return self::loadPrecompiled($L, $chunk, '@' . $filename, $mode);
    }

    /**
     * lua_load of a Lua file bin/lua2php transpiled, with chunk name
     * $chunkname. $chunk is what its generated file returns:
     *
     *     'format'  => PRECOMPILED_FORMAT
     *     'binary'  => whether the Lua file was a binary chunk
     *     'nesting' => how deep its parser's nesting went (Compiler::compile)
     *     'error'   => null, or [status, message, whether the message
     *                  follows the chunk's name] of the error it raises
     *                  when loaded (it did not compile)
     *     'protos'  => its Protos as a Lua binary chunk (null with an error)
     *     'factory' => the factory of its PHP code (see Emitter; null with an error)
     *
     * lua2php cannot know which path will find the file, so the chunk
     * name (in Protos compiled from text and in error messages) is set
     * here, as lua5.4 would set it.
     */
    public static function loadPrecompiled(Coroutine $L, array $chunk, string $chunkname, ?string $mode): LuaClosure
    {
        [$status, $result] = Calls::protectedRun($L, static function () use ($L, $chunk, $chunkname, $mode): LuaClosure {
            self::checkMode($mode, $chunk['binary'] ? 'binary' : 'text');
            $nestingError = self::nestingError($L->nCcalls, $chunk['nesting']);
            if ($nestingError !== null) {
                throw $nestingError;
            }
            if ($chunk['error'] !== null) {
                [$errorStatus, $message, $followsName] = $chunk['error'];
                if ($followsName) {
                    $message = ($chunk['binary'] ? Undump::nameForErrors($chunkname) : ChunkId::of($chunkname)) . $message;
                }
                throw new LuaError($message, $errorStatus);
            }
            $proto = Undump::undump($chunk['protos'], $chunkname, !$chunk['binary']);
            if (!$chunk['binary']) {
                self::setSource($proto, DebugInfo::cString($chunkname));  // a binary chunk keeps its own
            }
            return self::instantiate($proto, $chunk['factory']);
        }, $L->errfunc);
        if ($status !== Lua::LUA_OK) {
            throw new LuaError($result, $status);
        }
        $closure = $result;
        if ($closure->proto->upvalues !== []) {  // does it have an upvalue?
            $closure->getUpval(0)->v = $L->globalState->globals;  // set it to the global table
        }
        return $closure;
    }

    /** sets the source of $proto and the functions in it (lparser.c: open_func gives them all the lexer's) */
    private static function setSource(Proto $proto, string $source): void
    {
        $proto->source = $source;
        foreach ($proto->p as $child) {
            self::setSource($child, $source);
        }
    }

    /**
     * lauxlib.c: luaL_loadfilex's fopen of $filename (errno as C's), or
     * the LuaError(LUA_ERRFILE) "cannot open <name>: <strerror>".
     */
    private static function openFile(string $filename): CFile
    {
        Errno::$errno = 0;
        $file = CFile::open($filename, 'r');
        if ($file === null) {
            throw new LuaError("cannot open $filename: " . Errno::strerror(Errno::$errno), Lua::LUA_ERRFILE);
        }
        return $file;
    }
}
