-- error values of every type, levels and positions
print(pcall(error))
print(pcall(error, nil))
print(pcall(error, 42))
print(pcall(error, 4.5))
print(pcall(error, true))
local t = {}
local ok, value = pcall(error, t)
print(ok, value == t)
print(pcall(error, "msg"))
print(pcall(error, "msg", 0))
print(pcall(error, "msg", 1))
print(pcall(error, "msg", 2))
local function level1() error("from level1", 1) end
local function level2() error("from level2", 2) end
local function callsLevel2() level2() end
print(pcall(level1))
print(pcall(level2))
print(pcall(callsLevel2))
print(pcall(function () error("nested", 3) end))
print(pcall(function () error(setmetatable({}, {__tostring = function () return "TS" end})) end))
print(pcall(assert, false))
print(pcall(assert, nil, "custom"))
print(pcall(assert, false, 42))
print(pcall(assert, 1, 2, 3))
print(pcall(assert))
print(pcall(function () assert(false) end))
print(pcall(function () assert(false, "with message") end))
print(pcall(function () assert(nil, {}) end))
-- runtime error messages with variable information
local up = nil
local function useUp() return up.field end
print(pcall(useUp))
print(pcall(function () return undefinedGlobal.field end))
print(pcall(function () local tab = {}; return tab.a.b end))
print(pcall(function () local tab = {}; return tab[1][2] end))
print(pcall(function () local tab = {}; local key = "k"; return tab[key].x end))
print(pcall(function () local s = "str"; return s.x.y end))
print(pcall(function () return ("x")() end))
print(pcall(function () local n = 1; n() end))
print(pcall(function () local tab = {}; tab.f() end))
print(pcall(function () local tab = {}; tab:m() end))
print(pcall(function () up() end))
print(pcall(function () math.nofunction() end))
print(pcall(function () local a = {} ; return a + 1 end))
print(pcall(function () local a = "x"; return a + 1 end))
print(pcall(function () return 2 ^ {} end))
print(pcall(function () local a; for i = a, 10 do end end))
print(pcall(function () for i = 1, "x" do end end))
print(pcall(function () for i = 1, 10, 0 do end end))
print(pcall(function () for i = 1.0, 10, 0 do end end))
print(pcall(function () for i = 1, 10, {} do end end))
print(pcall(function () local x = {} .. {} end))
print(pcall(function () return math.huge // 0 end))
print(pcall(setmetatable, 1, {}))
print(pcall(setmetatable, {}, 1))
print(pcall(rawset, {}, nil, 1))
print(pcall(rawset, {}, 0/0, 1))
print(pcall(function () local tab = {}; tab[nil] = 1 end))
print(pcall(function () local tab = {}; tab[0/0] = 1 end))
print(pcall(next, {}, "nokey"))
print(pcall(ipairs))
print(pcall(rawlen, 5))
print(pcall(rawget, "x", 1))
print(pcall(select, "x"))
print(pcall(math.floor, "a"))
print(pcall(math.max))
print(pcall(table.insert, {}, 1, 2, 3))
print(pcall(table.insert, {}, 5, 1))
print(pcall(table.concat, {1, {}, 3}))
print(pcall(tostring))
print(pcall(type))
print(pcall(setmetatable, {}))
