<?php
// Not generated by lua2php: an ordinary PHP file where a Lua module "helper"
// would be precompiled. The transpiled project must neither run it nor
// take it for the module.
echo "FOREIGN PHP RAN\n";
return ['format' => 'luaphp-chunk-1'];
